[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "chaosbeatsapp://"
additional_redirect_urls = ["https://*"]
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = true
client_id = ""
secret = ""
redirect_uri = "chaosbeatsapp://auth/callback"

[storage]
enabled = true
file_size_limit = 52428800

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083
